[project]
name = "lib-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "heiwa4126", email = "heiwa4126@gmail.com" }]
requires-python = ">=3.12"
dependencies = []

# [project.scripts]
# lib-a = "lib_a:main"

[build-system]
requires = ["uv_build>=0.11.32,<0.12.0"]
build-backend = "uv_build"
